name: LanguageAPI
version: "2.0"
main: de.max_overlack.languageapi.LanguageAPIPlugin
api-version: "1.0.0"
authors: ["Majo", "nosooqua"]
description: Allows plugin developers to easily support multiple languages.